name: Deploy to ECR

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get current version
        id: build-helper
        run: |
          PACKAGE_JSON_PATH="${1-.}"
          echo ::set-output name=current-version::$PACKAGE_VERSION

      - name: Build, tag, and push image to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          ECR_REGISTRY: public.ecr.aws/d7d0z8s1
          ECR_REPOSITORY: guahanweb/twitter-relay-service
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
          IMAGE_TAG=$(cat ./package.json | jq '.version' | tr -d '"')
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
